const CONST = {
    LEFT: "LEFT",
    RIGHT: "RIGHT",
    CENTER: "CENTER",
    LOWER: "LOWER",
    UPPER: "UPPER",
    NARRATOR: '"Narrator"',
    SETTINGS: '"Settings"',
    PARENTHESIS: '"Parenthesis"',
    NAME: '"Name"',
    REPLIQUE: '"Replique"',
    DEFAULTTITLE: "Default Title",
    DEFAULTSOUNDSFOLDER: './sounds/',
    DEFAULTLANG: 'en',
    DEFAULTTMPFOLDER: './tmp/',
    MP3: 'mp3',
    DEFAULTLINEWIDTH: 72,
    DEFAULTAUDIOFREQUENCY: 24000,
    DEFAULTGAIN: 1,
    DEFAULTPITCH: 1,
    DEFAULTRATE: 0.99,
    HYPHEN: "-",
    HYPHENHINT: "--",
    SPECIALMATCH: /[\.!?;:,] /g,
    GTTSMAXIMUM: 100,
};

export default CONST;